### ISSUE TITLE
LRP for semantic segmentation

### ISSUE THREAD

**Issue by bugsuse** [hans66hsu/nn_interpretability#1]
Nice work! I want to apply LRP to unet model for explaining semantic segmentation tasks. I looked up most implementations of the Pytorch version of LRP and almost none of them support semantic segmentation tasks. Does the LRP in this resource support the interpretation of semantic segmentation tasks? Thanks a lot!

**Comment by hans66hsu** [comment]
The current focus of the examples is classification tasks. To extend it to segmentation tasks you would have to change the network to a fully convolutional network but the LRP rule in our package should be applicable.
