### ISSUE TITLE
LRP for time series forecasting

### ISSUE THREAD

**Issue by ihiratanveer** [hans66hsu/nn_interpretability#5]
Hi, 
Thanks for the well explained implementations. I want to apply LRP to LSTM for a multivariate time series forecasting task (to predict future values for multiple consecutive days). Will this LRP implementation support the forecasting tasks when the data is tabular?

**Comment by hans66hsu** [comment]
Thanks for your interest. The implementation only contains LRP rule for fully connected layers, convolutional layers, and pixel domains since this repo only supports visualization on images. Visualizing the relevance score on tabular and using LSTM is beyond the implementation of this repo.
